### ISSUE TITLE
book error?

### ISSUE THREAD

**Issue by VaporeonScripts** [Lance5057/ExtraDelight#138]
[19nov2024 19:17:23.547] [modloading-worker-0/ERROR] [patchouli/]: Failed to load book extradelight:cookbook defined by mod extradelight, skipping
java.lang.IllegalArgumentException: Book extradelight:cookbook has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at TRANSFORMER/patchouli@1.21-87-NEOFORGE-SNAPSHOT/vazkii.patchouli.common.book.Book.<init>(Book.java:146) ~[Patchouli-1.21-87-NEOFORGE-SNAPSHOT.jar%231122!/:1.21-87-NEOFORGE-SNAPSHOT]
	at TRANSFORMER/patchouli@1.21-87-NEOFORGE-SNAPSHOT/vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[Patchouli-1.21-87-NEOFORGE-SNAPSHOT.jar%231122!/:1.21-87-NEOFORGE-SNAPSHOT]
	at TRANSFORMER/patchouli@1.21-87-NEOFORGE-SNAPSHOT/vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[Patchouli-1.21-87-NEOFORGE-SNAPSHOT.jar%231122!/:1.21-87-NEOFORGE-SNAPSHOT]
	at java.base/java.util.HashMap.forEach(Unknown Source) ~[?:?]
	at TRANSFORMER/patchouli@1.21-87-NEOFORGE-SNAPSHOT/vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[Patchouli-1.21-87-NEOFORGE-SNAPSHOT.jar%231122!/:1.21-87-NEOFORGE-SNAPSHOT]
	at TRANSFORMER/patchouli@1.21-87-NEOFORGE-SNAPSHOT/vazkii.patchouli.neoforge.common.NeoForgeModInitializer.onInitialize(NeoForgeModInitializer.java:86) ~[Patchouli-1.21-87-NEOFORGE-SNAPSHOT.jar%231122!/:1.21-87-NEOFORGE-SNAPSHOT]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2367!/:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar%2367!/:?]
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:158) ~[loader-4.0.31.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.ModLoader.lambda$dispatchParallelEvent$4(ModLoader.java:172) ~[loader-4.0.31.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.31.jar%2360!/:4.0]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]

**Comment by Lance5057** [comment]
It is broken currently yes, it shouldn't effect anything though.

nice username btw

**Comment by VaporeonScripts** [comment]
> nice username btw

ty ig? xd

**Comment by Lance5057** [comment]
ig?

**Comment by VaporeonScripts** [comment]
are u referring to "vaporeonScripts"? xd

**Comment by Lance5057** [comment]
yeah, thats my favorite pokemon

**Comment by VaporeonScripts** [comment]
oh, lmao

**Comment by Lance5057** [comment]
Anyway, the book is WIP and the error doesn't effect anything so it'll get fixed eventually someday probably.
